# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95b6a8f1a1383f0f25f9603c4a07e7362d3518ca6848f2d9b3afb412679a2341708c57c33016c834ef606d1e9e273824340443ff57200320184aa7bec40ee724

test:
  secret_key_base: c87b516aff13b1024ca73f1130caa4883456f81d238c6411a72a66038434ae830b64e78ac0d314395e57e64ad87587fbc403c972ef234e1debd198fb3060e0cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
